//
//  LibraryView.swift
//  Momiji
//
//  Created by Lennart Kotzur on 04.09.25.
//

import SwiftUI
import UniformTypeIdentifiers

struct Work: Identifiable, Hashable {
    let id: UUID = .init()
    let url: URL
    var hash: String?
}

struct LibraryView: View {
    @State private var works: [Work] = []
    @State private var showImporter = false
    @State private var selectedWork: Work?

    var body: some View {
        NavigationSplitView {
            List(works) { w in
                Button {
                    selectedWork = w
                } label: {
                    VStack(alignment: .leading) {
                        Text(w.url.lastPathComponent).lineLimit(1)
                        if let h = w.hash {
                            Text(h.prefix(12) + "…").font(.caption).foregroundStyle(.secondary)
                        }
                    }
                }
            }
            .navigationTitle("Momiji")
            .toolbar { Button("Import") { showImporter = true } }
            .fileImporter(isPresented: $showImporter,
                          allowedContentTypes: [.zip, .folder]) { res in
                if case let .success(url) = res {
                    Task { await importURL(url) }
                }
            }
        } detail: {
            if let w = selectedWork, let reader = try? ZipOrFolderReader(url: w.url) {
                ReaderView(reader: reader, title: w.url.lastPathComponent)
            } else {
                ContentUnavailableView("Select a work", systemImage: "books.vertical")
            }
        }
    }

    @MainActor
    private func importURL(_ url: URL) async {
        var w = Work(url: url)
        if url.startAccessingSecurityScopedResource() {
            defer { url.stopAccessingSecurityScopedResource() }
            // Swift symbol generated by UniFFI from namespace momiji.core:
            w.hash = MomijiCoreSha256File(url.path)
        }
        works.append(w)
    }
}
